config/routes.rb
Rails.application.routes.draw do
  get 'room_users/index'
  get 'rooms/index'
  get 'users/account'
  get 'rooms/posts'
  get 'rooms/search'
  devise_for :users
  root 'users#index'
  resources :users
  resources :rooms
  resources :room_users

  # Rails.application.routes.draw do
  #   devise_for :users
  # end

  # devise_for :users,controllers: {

  # }

  # devise_scope :user do
  #   get '/user/sign_out' => 'devise/session#index'
  #   post '/user/' => 'users/registrations#users_account'
  # end
end

app/views/shared/_account_sidebar.html.erb
<div class="sidebar_container">
  <ul id="account_sidebar">
    <li class="<%= 'active' if current_page?(users_account_path) %>"><%= link_to "アカウント",users_account_path, class: "account_sidebar_list" %></li>
    <li class="<%= 'active' if current_page?(edit_user_path(current_user.id)) %>"><%= link_to "プロフィール",edit_user_path(current_user.id), class: "account_sidebar_list" %></li>
  </ul>
</div>
 

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div,value, class: "#{key}") %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer_view">&copy; 2020 POTEPAN.INC.</div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="header-top">
    <div class="header-left">
      <div class="header-top-img">
        <%= link_to image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"),"/" %>
      </div>
      <%= form_with url: rooms_search_path,method: :get do |f| %>
        <div class="search-boxes">
          <div class="search-box-area">
            <%= f.text_field :area,placeholder:"エリア" %>
            <span class="icon"><i class="fa fa-map-marker" aria-hidden="true"></i></span>
          </div>
          <div class="search-box-keyword">
            <%= f.text_field :keyword,placeholder:"キーワード" %>
            <span class="icon"><i class="fas fa-search"></i></span>
          </div>
        </div>
        <%= f.submit"",class:"display_none" %>
      <% end %>
    </div>
    <div class="header-right">
      <% if user_signed_in? %>
          <p class="login_name"><%= current_user.name%></p>
          <div class="avatar">
            <div class="profile-image">
              <% if current_user.avatar.attached? %>
                <%= image_tag(url_for(current_user.avatar)) %>
              <% else %>
                <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg">
              <% end %>
            </div>
            <ul id="account-menu">
              <li><%= link_to 'ルーム登録',new_room_path %></li>
              <li><%= link_to '予約済みルーム一覧',room_users_path %></li>
              <li><%= link_to '登録済みルーム一覧',rooms_posts_path %></li>
              <li><%= link_to '設定',users_account_path %></li>
              <li><%= link_to 'ログアウト',destroy_user_session_path,method: :delete %></li>
            </ul>
        </div>
      <% else %>
        <%= link_to 'ログイン',new_user_session_path,class:"btn login-btn" %>
        <%= link_to '登録する',new_user_registration_path,class:"btn signup-btn" %>
      <% end %>
    </div>
  </div>
</header>