config/routes.rb
Rails.application.routes.draw do
  get 'room_users/index'
  get 'rooms/index'
  get 'users/account'
  get 'rooms/posts'
  get 'rooms/search'
  devise_for :users
  root 'users#index'
  resources :users
  resources :rooms
  resources :room_users

  # Rails.application.routes.draw do
  #   devise_for :users
  # end

  # devise_for :users,controllers: {

  # }

  # devise_scope :user do
  #   get '/user/sign_out' => 'devise/session#index'
  #   post '/user/' => 'users/registrations#users_account'
  # end
end

app/models/room.rb
class Room < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :room_users, dependent: :destroy
  has_many :rooms, through: :room_users
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def new
    @room =Room.new
  end

  def create
    @room = Room.new(params.require(:room).permit(:name,:introduction,:cost,:address,:image,:user_id))
    if @room.save
      redirect_to action: :show,id: @room.id
      flash[:notice] = "Room was successfully created."
    else
      render "new_room"
    end
  end
  
  def show
    @room = Room.find(params[:id])
    if user_signed_in?
      @user = User.find_by(id:current_user.id)
    end
  end

  def posts
    @rooms = Room.where(user_id:current_user.id)
  end

  def search
    @area = Room.where("address LIKE ?","%#{params[:area]}%")
    @area_s = @area.where("introduction LIKE ?","%#{params[:keyword]}%")
    @counter = @area_s.count
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<h1>Rooms#index</h1>
<p>Find me in app/views/rooms/index.html.erb</p>

app/views/rooms/new.html.erb
<div class="account_container">
  <div class="account_left">
    <div class="sidebar_container">
      <ul id="account_sidebar">
        <li class="active"><p>基本情報</p></li>
      </ul>
    </div>
  </div>
  <div class="account_right">
    <div class="user_view_box">
      <div class="update_content">
        <h3><p class="account_sidebar_list">ルーム情報登録</p></h3>
      </div>
      <%= form_with model: @room do |f| %>
        <%= f.hidden_field :user_id,value:current_user.id %> 
        <div class="update_content">
          <div class="row">
            <div class="col-md-3"><%= f.label :name, "ルーム名",class:"font-weight-bold"%><span class="account_label">必須</span></div>
            <%= f.text_field :name,placeholder: "ルーム名を入力", required: true ,class:"col-md-9" %>
          </div>
        </div>
        <div class="update_content">
          <div class="row">
            <div class="col-md-3"><%= f.label :introduction, "ルーム紹介",class:"font-weight-bold" %><span class="account_label">必須</span></div>
            <%= f.text_area :introduction,placeholder: "ルーム説明を入力", required: true ,class:"col-md-9" %>
          </div>
        </div>
        <div class="update_content">
          <div class="row">
            <div class="col-md-3"><%= f.label :cost, "料金",class:"font-weight-bold" %><span class="account_label">必須</span></div>
            <%= f.text_field :cost,placeholder: "一日あたりの料金を入力", required: true ,class:"col-md-9" %>
          </div>
        </div>
        <div class="update_content">
          <div class="row">
            <div class="col-md-3"><%= f.label :address, "住所",class:"font-weight-bold" %><span class="account_label">必須</span></div>
            <%= f.text_field :address,placeholder: "住所を入力", required: true ,class:"col-md-9" %>
          </div>
        </div>
        <div class="update_content">
          <div class="row">
            <div class="col-md-3"><%= f.label :image, "ルーム画像",class:"font-weight-bold" %><span class="account_label">必須</span></div>
            <%= f.file_field :image, required: true ,class:"col-md-9" %>
          </div>
        </div>
        <div class="update_content">
          <div class="row">
            <%= f.submit "登録",class:"col-md-2 btn-primary btn-password-edit" %>
          </div>
        </div>
      <% end %>    
    </div>
  </div>
</div>

app/views/rooms/posts.html.erb
<div class="room_posts_container">
  <div class="room_chart">
    <h3 class="pb-3 mb-1">登録済みルーム一覧</h3>
    <table class="posts_table">
      <thead>
        <tr class="text-center posts_table_th">
          <th>ルーム画像</th>
          <th>ルーム名</th>
          <th>ルーム紹介</th>
          <th>料金</th>
          <th>作成日</th>
        </tr>
      </thead>
      <tbody>
        <% @rooms.each do |room| %>
          <tr class="posts_table_td">
            <td class="posts_img">
              <% if room.image.attached? %>
                <%= image_tag(url_for(room.image)) %>
              <% end %>
            </td>
            <td><%= link_to "#{room.name}",room_path(room.id),class:"posts_name" %></td>
            <td><%= room.introduction %></td>
            <td>¥ <%= room.cost %></td>
            <td><%= room.created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/rooms/search.html.erb
<div class="search_page_inner">
  <h3>検索結果：<%= @counter %>件</h3>
  <div class="row">
    <% @area_s.each do |area|  %>
      <div class="col-sm-6 col-lg-4 col-xl-3 search_content">
        <div class="search_inner">
          <%= link_to room_path(area.id) do %>
            <% if area.image.attached? %>
              <%= image_tag(url_for(area.image)) %>
            <% end %>
            <div class="search_text_inner">            
              <h3><%= area.name %></h3>
              <h4><%= area.introduction %></h4>
              <p>¥ <%= area.cost %></p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="room_show">
  <div class="row">
    <div class="col-md-8">
      <div class="room_show_img">
        <%= image_tag(url_for(@room.image))%>
      </div>
      <div class="room_show_detail">
        <div class="room_show_profile_img">
          <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg">
        </div>
        <div class="room_show_profile">
          <div class="room_show_name">
            <%= @room.name%><br>
          </div>
          <div class="room_show_address">
            <%= @room.address%>
          </div>
        </div>
      </div>
      <div class="room_show_introduction">
        <%= @room.introduction %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="room_reserve_container">
        <h3>¥ <%= @room.cost %> / 日</h3>
        <%= form_with url: new_room_user_path,method: :get do |f| %>
          <%= f.hidden_field :room_id,value: @room.id %>
          <% if user_signed_in? %>
            <%= f.hidden_field :user_id,value: @user.id %>
          <% end %>
          <%= f.label :start_date,"開始日"%><br>
          <%= f.date_field :start_date,required: true %><br>
          <%= f.label :end_date,"終了日" %><br>
          <%= f.date_field :end_date,required: true %><br>
          <%= f.label :people,"人数" %><br>
          <%= f.number_field :people,required: true %>
          <% if user_signed_in? %>
            <%= f.submit "予約する",class:"btn-primary btn-password-edit col-md-2" %> 
          <% else %>
            <%= link_to 'ログイン',new_user_session_path,class:"btn-primary btn-password-edit col-md-2"%>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>